### ISSUE TITLE
[BUG] Unlimited zPage without having 0.01 ZEC?

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#10]
### Contex:

According to the specifications on the About Free2z website, a Creator can initially only create up to 3 zPage, to create unlimited zPage it must accumulate at least 0.01 ZEC as a sum of those 3 zPage.

### About the error:

**Steps to reproduce**
1. Being at the limit to create zPage press on the Create new zPage button.
![Create-New-zPage](https://user-images.githubusercontent.com/37910384/169348790-ab28b718-ad5c-4d3e-95bc-28572e597a09.png)
2. The page reloads and shows you a message indicating that you cannot create more zPage because you are at the limit.
![photo_2022-05-19_11-17-13](https://user-images.githubusercontent.com/37910384/169349221-af5475d5-93e3-447e-b3e0-b96405639cbb.jpg)

3. Repeat step 1 and 2 and you will get to a point where it tries to load a new zPage but then displays the window indicating that you are limited.
4. Fund some of your pages until you reach 0.01 ZEC so you can create new zPages.
5. Click on Create new zPage or go directly to the list of your zPages, you will see that those or some of those actions performed while you were limited were effective and several zPages were created/started.
![photo_2022-05-19_09-24-57](https://user-images.githubusercontent.com/37910384/169350910-a3d51caf-b098-4407-95a2-5e0808b7c1c2.jpg)

**Expected behaviour**

Somehow it is necessary to avoid that requests to create new zPage are not effective while the user is at the limit.

**Actual behaviour**

Some new zPage creation requests are effective while the user is in the limit.

_Although I'm not sure how to fix it, I hope that if it's a bug you can fix it, I congratulate you for the new features, are great._

_Long live Free2z!_ ❤️🛡

**Comment by skyl** [comment]
Interesting, yeah. Initially we needed to create the zPage before even loading the edit page because the initial design was that each page would have it's own address in the F2Z wallet. https://free2z.cash/scaling-with-zip-0321

But, this could be refactored to only create the page once it is valid with a title. I don't like how test pages can get created and can accumulate without titles - then when you go to use one, the "created_at" datetime is old ...

Also, there is no pagination on the "/list" your pages; so, if you create too many you can't easily get to them :/. So, we have several things to improve in these areas.

**Comment by skyl** [comment]
Also the "RBAC" logic for who sees what is a little bit complicated and haphazard right now - and it should be formalized and unit tested.

**Comment by Edicksonjga** [comment]
>  ...this could be refactored to only create the page once it is valid with a title.

Yes, it would be good to improve this part because a user who is eager to create a zPage but has no idea of the initial limit (3 zPage until 0.01 ZEC is accumulated between all of them) can press again and again that 'Create...' button and after exceeding the limit he/she would find a list of zPage full of pages that he/she doesn't know where they came from.

> I don't like how test pages can get created and can accumulate without titles - then when you go to use one, the "created_at" datetime is old...

I joked with Roosevelt privately about the 'Created' - 'Edited' dates when I told him about the error 😁.
![Sin título2](https://user-images.githubusercontent.com/37910384/169705030-5f71fa1b-34d2-4376-9617-121bad096daa.png)

I'm not sure if this affects the ranking of a zPage, regarding pagination, it would be a great improvement for the creator to have better access to their zPage.

Thank you very much for your response and congratulations on the approval of the funding by ZCG.
**Long live Free2z! 👍🏽👍🏽**

**Comment by skyl** [comment]
"your zpages" pagination - https://github.com/free2z/free2z/projects/1#card-80921803

don't create invalid dummy pages - https://github.com/free2z/free2z/projects/1#card-82471425

**Comment by skyl** [comment]
I need to take a pass at the documentation - a lot of things have changed since this issue

**Comment by skyl** [comment]
We will go through the docs soon and remove this. Unlimited zpages hasn't been a problem.
