### ISSUE TITLE
Problems with Zpages series

### ISSUE THREAD

**Issue by gordonesroo** [free2z/zuu#104]
Greetings! I have detected a bug that puzzles me and does not let me organize my Zpages in series. I do not know if it has to do with a maximum number of series that I can have?

But I just created a series of my Europe tour, and when I create a new Zpage and try to add it to that series, the drop-down list doesn't show it to me. The interesting thing is that yes, the series is created, but it doesn't come up for me to add new Zpages. It's really crazy.
![Captura de pantalla de 2024-10-18 00-53-33](https://github.com/user-attachments/assets/3e0576de-cf14-4e85-bcf3-89ef0bb73267)

**Comment by skyl** [comment]
It's probably because the list is paginated.

**Comment by gordonesroo** [comment]
Thanks! That's cool!
