### ISSUE TITLE
Better options to share the zPages

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#28]
Recently at the [Free2z Nights of the Zcash community](https://twitter.com/zcashesp/status/1581074473679482880?t=P8s7-qJXoTQwH9JoXnIfyA&s=19), Aura Brito suggested that **Free2z** should have **_better sharing options for zPages_**, which make it easier to share to other social networks.

A platform like [zemeteam](zeme.team) (from the Zcash ecosystem) has a share button to Twitter, we know that Twitter is where most of the people who follow or use Zcash are concentrated.

Free2z although it has a share button, the function of this is only to copy the link, there are no more options when you tap on that button.

![IMG_20221018_140418_348](https://user-images.githubusercontent.com/37910384/196509605-4afe9269-a562-42fb-880d-891954c4c7c1.jpg)

I suggest to somehow implement in that button more options to share the zPage in other social networks.

![InShot_20221018_153517906](https://user-images.githubusercontent.com/37910384/196527063-885872ef-8cf5-4209-9d9a-749a52c5d1ab.jpg)

It could also be a new horizontal bar at the end of the zPage or floating and vertical on the left or right side.

Surfing the internet by mere chance I came across this service that is compatible with ReactJS:

https://sharethis.com/es/
https://stagewp.sharethis.com/es/support/installation/how-to-install-sharethis-tools-on-reactjs/

Other open source alternatives:
https://github.com/topics/share-buttons

The intention is that users after creating their zPages have an option that encourages them to share on social networks where they make life, a button that only copies the link can be the stone in the shoe for those who need something more accessible, comfortable or easy to use.

**Comment by skyl** [comment]
I don't really think putting "sharethis" on free2z is worth the privacy cost.

https://sharethis.com/privacy/

What services would you like easier share on specifically?

I could see using something Ike this: https://github.com/nygardk/react-share but it's not sort of all-in-one OOTB solution for everything like "sharethis" is.

**Comment by Edicksonjga** [comment]
Note:

After reading and testing different pages with share buttons, the implementation in Free2z should use the system's Share options (that menu that opens when you tap on the Share option that the browser brings up), as in the image.

![Screenshot_20221022-173714](https://user-images.githubusercontent.com/37910384/197365168-9203bda8-18ce-48f4-b9e7-452da5418716.jpg)

This would apply to both mobile devices and Desktop (at least it works with Windows, I know very little about Linux and nothing about macOS).

Curiously reading an article about 'Share React Native' on docs.w3cub.com, your option to share the article caught my attention as it shows various buttons from different social networks and also a button that opens the system menu, watch the video .

https://user-images.githubusercontent.com/37910384/197365173-0bcc6762-53c5-4a17-9ad3-77b3f1a3148d.mp4
👍👍👍

**Comment by skyl** [comment]
hrm interesting; yeah, I think that would be the ideal way - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

but, for some reason it doesn't seem to work at first try

<img width="687" alt="Screen Shot 2022-10-23 at 5 30 22 PM" src="https://user-images.githubusercontent.com/61438/197426261-f094d231-f849-49c3-ad2b-092e4b133637.png">

I'll see what I can do later. I think the native browser capabilities would definitely be better than a 3rd party plugin

**Comment by Edicksonjga** [comment]
Yes, browsers on mobile devices already offer a Share button that opens that system menu.

Still, I'm betting on having a better Share button, don't you think that button is missing something in Free2z?

> As our applications become more interconnected, it is increasingly important for our users to be able to share content with other applications — and thus, other audiences.

For me, that is a pretty apt paragraph of this good [article](https://blog.logrocket.com/sharing-content-react-native-apps-using-react-native-share/) .

**Comment by skyl** [comment]
"React Native" is fundamentally different than react web - I try to avoid React Native for the most part.

**Comment by Edicksonjga** [comment]
> "React Native" es muy diferente a React Web: trato de evitar React Native en su mayor parte.

I don't know anything about programming, I'll pass that on to you because of what it says about the use of Share according to different points of view.

The way or the language in which you program is something that is beyond my knowledge hahahaha.

I'm sure you'll achieve something great if they decide to improve the Share button.

**Comment by skyl** [comment]
Hrm, it turns out to be really easy and pretty nice, I think: https://www.geeksforgeeks.org/how-to-activate-web-share-using-react-web-share-in-reactjs/

Let's see how it blends ...

**Comment by skyl** [comment]
It's maybe not quite as nice as your images but check it out and see what you think.

https://twitter.com/free2zcash/status/1586246975879421952

**Comment by skyl** [comment]
If I could tell at nginx if the requestor is a social media robot or a real human, I wouldn't need to have a different url for robots and humans but this seems easier said than done.

**Comment by skyl** [comment]
Having different url is bad. Much better would be to give crawler user agent requests synchronous header content - https://stackoverflow.com/questions/51294553/nginx-proxy-or-root-depending-on-user-agent

**Comment by skyl** [comment]
Deploying another improvement here. Time for a final pass to see if there is anything that can be improved @Edicksonjga
