### ISSUE TITLE
Names or descriptive labels

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#31]
There are several situations in which a button, dialog, or other feature on a website should be given a descriptive name or label in order to enable assistive technology users to understand its purpose.

In Free2z there are buttons or elements that do not have descriptive labels, which makes it difficult for people who require assistive technology to better understand the interface or the different functions to use the platform.

- From a zPage display two of the three buttons have a label, the Share button does not.

![InShot_20221030_145907372](https://user-images.githubusercontent.com/37910384/198897238-405c92f9-80f7-4954-8ce3-8b4330a7e9d3.jpg)

- From the search engine, the button to filter the Verified pages has its respective label, the other two buttons do not.
![InShot_20221030_145940800](https://user-images.githubusercontent.com/37910384/198897334-7153ef67-323e-43a5-b138-0f602010c789.jpg)

- From the List, the buttons on the bar have descriptive labels, but the button to enter the profile does not.
![InShot_20221030_150028965](https://user-images.githubusercontent.com/37910384/198897384-67e53a23-4803-4d21-9f15-ba75a4963936.jpg)

In the following tweet you can see how a visually impaired Free2z user has found out on social media that the Share option has been improved, but she does not identify where the option is since the button does not have a descriptive label.

https://twitter.com/lehnautora/status/1586497572843278336

An issue was also previously reported in the use of Markdown in Free2z related to alt texts in images/videos used to describe the medium in question, you can read about that issue [here](https://github.com/free2z/zuu/issues/9) .

Grateful for the improvements that have been added recently and those that will surely continue to come.

I hope that soon they can correct the aforementioned errors to improve the user experience that require descriptive technologies to identify the functions that Free2z offers us.

**Comment by skyl** [comment]
Thanks for the report!

**Comment by skyl** [comment]
Added to share button - this is good LHF to get started with react.
