### ISSUE TITLE
Suggestions: Best profile for the Creator

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#33]
The creator should have a better profile on Free2z and have the options:

- Avatar and cover
- Full name
- Description or biography
- Three-point menu where the options will be located
- Button to Follow or Subscribe to the Creator and thus receive notifications
- Button to donate or send memos from the profile and thus not have to enter a zPage
- Redesign of zPages list with thumbnails
- Button to change the view of the zPages list

![IMG_20221114_233937_105](https://user-images.githubusercontent.com/37910384/201826648-2d65120f-d80c-49d6-b499-562b5e5ed547.jpg)

From the creator page the user will be able to carry out different actions depending on who they are, such as Editing the pages and managing the profile if they are the Creator or reading and sharing if they are the reader.

So far the Creator page lacks many features and only shows a basic list of created zPages, [here you can see how it is displayed](free2z.cash/creator/Edicksonjga).

### Best profile manager

Due to the aforementioned suggestions, it is evident that the options corresponding to each characteristics must be added in the profile manager.

![IMG_20221114_233940_978](https://user-images.githubusercontent.com/37910384/201826703-5d74ad28-8cf4-491b-b112-be565942454f.jpg)

- Option to select an image for the avatar and the cover
- Option to set a full name
- Option to add a description

These are the suggestions that I have recently thought of and wish they were on Free2z at some point, for more details you can read [this zPage](https://free2z.cash/zpage/sugerencia-mejor-perfil-para-el-creador).

I appreciate the willingness that they have always had to accept both the errors that we report and that they quickly correct, as well as the suggestions that we contribute.

**A greeting and long life to Free2z.**

**Comment by skyl** [comment]
- [ ] Avatar and cover
- [ ] Full name
- [ ] Description or biography
- [ ] Three-point menu where the options will be located
- [ ] Button to Follow or Subscribe to the Creator and thus receive notifications
- [ ] Button to donate or send memos from the profile and thus not have to enter a zPage
- [ ] Redesign of zPages list with thumbnails
- [ ] Button to change the view of the zPages list

**Comment by skyl** [comment]
~Button to change the view of the zPages list~ no need to complicate things with options - give the people what they don't know they want and give it to them in black

**Comment by skyl** [comment]
The interactions will be after 2Zs are made more useful

**Comment by Edicksonjga** [comment]
> ~Botón para cambiar la vista de la lista zPages~no es necesario complicar las cosas con opciones: dar a las personas lo que no saben que quieren y dárselos en negro

You are absolutely right, why give options for something old if something better is already being done. 👍👍👍

**Comment by Edicksonjga** [comment]
> * [x] Avatar y cubierta
> * [x] Nombre completo
> * [x] Descripción o biografía
> * [ ] Menú de tres puntos donde se ubicarán las opciones
> * [ ] Botón para seguir o suscribirse al Creador y así recibir notificaciones
> * [ ] Botón para donar o enviar notas desde el perfil y, por lo tanto, no tener que ingresar una página z
> * [x] Rediseño de la lista de páginas z con miniaturas
> * [x] Botón para cambiar la vista de la lista zPages

Definitely a great job they have done ❤️

**Comment by skyl** [comment]
Going to production now, will be there in 5 minutes

**Comment by skyl** [comment]
I think we can probably close this one and open up new issues for further improvements @Edicksonjga ?

**Comment by Edicksonjga** [comment]
> I think we can probably close this one and open up new issues for further improvements @Edicksonjga ?

How much time has passed, if my suggestion seemed great to me, what we have now is much better.

Yes, let's close this stage that has already been completed and go in search of more. 😎🤜🤛😎
