### ISSUE TITLE
Suggestion: Comments notification on profiles

### ISSUE THREAD

**Issue by zulamit** [free2z/zuu#34]
My suggestion is to receive some notification when we have new comments on our zpages.

The comments get lost most of the time because if someone has many zpages it's a bit complicated to check them all and it's always interesting to read the feedback that zcashers leave.

I hope this is an reachable proposal and not so complicated to add.

Thank you!

**Comment by skyl** [comment]
Thanks for the suggestion @zulamit we'll be working towards a notification feature and more interactions between creators (eg subscribe to creator). Inbox with activity on your pages would be great - comments, upvotes, etc ...

**Comment by skyl** [comment]
This particular one was done; but, there are more that need to be there:

- star (person you are subscribed to) made a converse/comment
- star went live

... Let us know what else is missing
