### ISSUE TITLE
Prevent multiple comments:

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#44]
I recently made a comment on a zpage, the comment didn't come out with the first tap (maybe because of bad internet connection) so I tapped the Comment button several times and then the same comment was also posted several times.

Add a mechanism to prevent multiple comments or I'll run out of 2Z 😁

**Attached image and link to comments:**
![Screenshot_20230303-234926.jpg](https://user-images.githubusercontent.com/37910384/222875176-47889cae-3eae-45b5-b425-0e51e3751927.jpg)

**zPage**: [¿Por qué Zcash necesita un podcast en español?](https://free2z.cash/gordonesroo/zpage/por-que-zcash-necesita-un-podcast-en-espanol#comment-150)

**Comment by skyl** [comment]
thanks, should be fixed in a few minutes ...
