### ISSUE TITLE
Improved progress bar

### ISSUE THREAD

**Issue by birdify** [free2z/zuu#45]
The existing progress bar works fine for short uploads such as text pdfs or images.  For videos or other large files, however, it is inadequate since the user doesn't have a clear idea what percentage of the file has been uploaded and if the upload is still proceeding (albeit slowly) or if there was some technical issue.  
Perhaps some way of indicating what percentage of the file has been uploaded could be helpful?

<img width="975" alt="progress bar" src="https://user-images.githubusercontent.com/59209004/222981299-1482d4a1-3a44-4be8-8c65-2b52a0573680.png">

**Comment by skyl** [comment]
facebook just has the original free2z indeterminate spinner though on web lol

**Comment by skyl** [comment]
> what percentage of the file

the progress is a visual percentage

**Comment by skyl** [comment]
> the user doesn't have a clear idea what percentage of the file has been uploaded

> Perhaps some way of indicating what percentage of the file has been uploaded could be helpful

nah, this is already world class - the eyeball is better at measuring percentage than the number-brain. Works great. Feel free to make a PR though.
