### ISSUE TITLE
Certificate issues 

### ISSUE THREAD

**Issue by birdify** [free2z/zuu#46]
I've noticed occasional privacy errors with Free2z.com over the past few weeks.  Maybe it's a certificate issue?

<img width="846" alt="privacy error" src="https://user-images.githubusercontent.com/59209004/222981378-f6e251e9-8ac3-4403-a24e-72197e78e705.png">

**Comment by skyl** [comment]
we don't support `www` right now. I don't really want to TBH but it seems like some things like to add it sometimes.

**Comment by skyl** [comment]
ChatGPT said I don't need to serve `www` at all. So, I just pulled it. I think that's fine. Hopefully 😱
