### ISSUE TITLE
Button to add media from media library to zPage

### ISSUE THREAD

**Issue by birdify** [free2z/zuu#48]
There is already a button to upload new files/images to a zPage inside the editor. This is a very helpful option.  However, some power users may have media assets that they have already uploaded that they would like to reuse.  It would be useful to have an additional button to grab something from your existing media library and add it to the post.

[Media button.pdf](https://github.com/free2z/zuu/files/10893710/Media.button.pdf)

**Comment by zerodartz** [comment]
Agree, was looking for it also once then understood it didnt exist.

**Comment by skyl** [comment]
This is done

<img width="95" alt="Screenshot 2023-09-21 at 10 01 38 PM" src="https://github.com/free2z/zuu/assets/61438/15e5c1be-d5bc-4e56-b94e-4b13522e67ab">
