### ISSUE TITLE
Login a user without case-sensitivity edge case

### ISSUE THREAD

**Issue by Cryptonativa** [free2z/zuu#53]
When I try to comment on another user's page, it asks me to log in to make a comment.

I enter my data (User name and password), then it does not recognize me, it sends me an error message saying that this user already exists. 

It should recognize that I'm logging into my account, not trying to make a new account-user. 

Look the notification at the top 👇🏽
![Screenshot 2023-04-11 at 8 49 13 PM](https://user-images.githubusercontent.com/128416795/231319629-614dfd27-4467-4dea-b888-ed8a5e06ecd8.png)

**Comment by skyl** [comment]
Your username is capitalized - I think this is an edge case having to do with case. Or, it may be that your password isn't right. Try with a capital C

**Comment by skyl** [comment]
you can try it now @Cryptonativa
