### ISSUE TITLE
#BUG: The images do not load in the StoryTime

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#55]
**Bug: Images generated by artificial intelligence do not load.**

Steps:
1. Enter StoryTime
2. Add a title to the story
3. Add a prompt and generate one or more images

**How it's working:**
When generating images in the StoryTime, they are not displayed in the editor, nor when publishing the story.

![Screenshot_20230413-000515](https://user-images.githubusercontent.com/37910384/231652845-dc1afdba-ae85-47cf-b719-1147b6218144.jpg)

**Expected performance:**
The generated image must be viewed in the editor and later when publishing the StoryTime.

**Other data:**
1. On the story thumbnail if the image is displayed.
2. The images generated if displayed in the uploaded media.
3. It only happens with new stories, in older stories if the images are displayed.

![Screenshot_20230413-000455](https://user-images.githubusercontent.com/37910384/231652937-09ee9822-54e7-4a1e-8f86-f3c86a6e86c4.jpg)
![Screenshot_20230413-000501](https://user-images.githubusercontent.com/37910384/231652952-38f459eb-9297-483a-93cc-07442d0e82d3.jpg)

¡Larga vida a Free2z! 😎

**Comment by skyl** [comment]
Nice find; fixed, thanks
