### ISSUE TITLE
Mobile vs desktop 

### ISSUE THREAD

**Issue by Cryptonativa** [free2z/zuu#56]
Los desarrolladores usan más desktop, pero los usuarios van a usar más los celulares para navegar free2z. Por lo tanto, el ambiente debe ser ideal y cómodo para el usuario desde el teléfono. 

["US adults spend five and a half hours daily in 2022 on their mobile phones. In 2022, mobile phones generate 60.66% of website traffic, while desktops and tablets are responsible for 39.34%. 55% of page views in 2021 came from mobile phones" ](https://techjury.net/blog/mobile-vs-desktop-usage/#:~:text=US%20adults%20spend%20five%20and,from%20mobile%20devices%20as%20well.)

**Comment by skyl** [comment]
I use the phone all the time. You'll have to be more specific. Everything works on mobile.

<img width="900" alt="Screenshot 2023-04-15 at 7 04 05 PM" src="https://user-images.githubusercontent.com/61438/232262233-bd013dfe-c0ba-47c6-a55e-ce35756d663d.png">

"Site should have good UX" <link to article about the importance of good UX>

**Comment by skyl** [comment]
Crazy thing. I've spent all my free time for over a year, every day using free2z on mobile and constantly making improvements to make sure that everything always works on mobile, and I didn't even realize that you can _already_ install it as an app on any platform - Mac, android, Linux, iOS, Windows ... And it all works great and looks great and has no broken styles. That doesn't happen without a lot of time and care. But, yeah, try that out.

![Screenshot_20230417_002221_Chrome](https://user-images.githubusercontent.com/61438/232432515-ef147007-e76b-4fff-ba72-abbba1929267.jpg)

![Screenshot_20230417_002232_Chrome](https://user-images.githubusercontent.com/61438/232432553-b5e054ae-23f3-4fc1-aedc-92d42326de65.jpg)

![Screenshot_20230417_002425_Chrome](https://user-images.githubusercontent.com/61438/232432615-af65018a-6d3c-4be6-98cd-ea82693013ff.jpg)


![Screenshot_20230417_002445_Chrome](https://user-images.githubusercontent.com/61438/232432669-8a38a153-124d-4241-9807-7cac9e872319.jpg)


![Screenshot_20230417_002455_Chrome](https://user-images.githubusercontent.com/61438/232432712-1e71def9-0751-4e38-bf74-259a325c2f66.jpg)


![Screenshot_20230417_013932_One UI Home](https://user-images.githubusercontent.com/61438/232432750-7e987ca7-5c16-40d2-8e0c-bbaa002749f6.jpg)

I've been prioritizing mobile in webapps for about 15 years now.

That kind of quality is not by accident.

I'm super curious what you guys are imagining that is so much better though. Probably just little changes that only take _more time and effort_.

**Comment by skyl** [comment]
Yeah, the icon should be better. Someone should do that.

Oh yeah, and I'm just going to package it and put it on app stores soon. Cool 😎

**Comment by zerodartz** [comment]
What browser has this install app feature? I dont seem to find it in any browser on ios.
