### ISSUE TITLE
Redirect in StoryTime

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#59]
Free2Z does not redirect the user when he tries to edit a StoryTime that is not his own through a link.

https://user-images.githubusercontent.com/37910384/233884328-b8dedcdd-70e8-476f-8c52-9c6d96ef6853.mp4

Although Storytimes are not the main use of the platform, it would be nice to get the same behavior as with zpages that redirects to the profile, or redirects to the Storytime section for the user to start creating stories.

It's not a case that can happen frequently, but the fact that the loading animation doesn't disappear can cause confusion for the user. 😎👍

**Comment by skyl** [comment]
I think these cases are mostly all fixed for authentication. One thing I notice is that the websocket can sometimes get doubled for double snackbars. But, It hink the login/logout is pretty smooth now?
