### ISSUE TITLE
Zpage list not updating

### ISSUE THREAD

**Issue by Edicksonjga** [free2z/zuu#61]
The zpage listing of a user's profile remains when you return to your profile.

Steps:
1. Enter the profile of a Creator
2. Open the menu and tap on Public to go to your profile
3. Check the list of zpages

https://user-images.githubusercontent.com/37910384/233978484-003b5973-21c3-4c2f-a98c-678839885e66.mp4

Expected behavior:
The zpages list should show the zPages you have created.

Current behavior:
The zpages list shows the zPages from the previous Creator.

The same happens in reverse, after being in your profile, refresh the page and then go back to the previous profile.

**Comment by skyl** [comment]
thanks!
