### ISSUE TITLE
Open in new tab homepage links

### ISSUE THREAD

**Issue by zulamit** [free2z/zuu#63]
Hi Zteam, I have something to say about the new design of f2z. First of all **it is very clean, I love it.**

But I noticed that when you want to open several pages simultaneously on a computer with the scroll click for example, or with the menu "open in new tab", it is not available, it doesn't do anything in that section.

![image](https://user-images.githubusercontent.com/111299875/234148755-d574d0ea-8702-422b-8fdd-eb2ebf914498.png)

Practically it is only possible to open one page at a time and then go back and return to the beginning.

This makes the user experience a bit uncomfortable and slow. I was used to do it in the previous version that can still be seen in find.

![image](https://user-images.githubusercontent.com/111299875/234149390-21312e05-47d5-4779-a5f7-8d8f670be897.png)

It will be nice to do it in this design.

Thanks.

**Comment by skyl** [comment]
Hey, thanks! it's true. I would also like to easily be able to save the images with right click. Thanks for the report

**Comment by skyl** [comment]
Part of #81 potentially.
