### ISSUE TITLE
Allow longer titles for zPages

### ISSUE THREAD

**Issue by birdify** [free2z/zuu#64]
zPage titles have a current limit of 128 characters. This means users can't add long titles (like on Medium and a lot of other blogging sites).

**Comment by skyl** [comment]
I guess you can have long titles on wordpress

https://skylar2z.wordpress.com/2023/06/19/testing-out-wordpress-for-real-testing-out-wordpress-for-real-testing-out-wordpress-for-real-testing-out-wordpress-for-real-testing-out-wordpress-for-real-testing-out-wordpress-for-real-testing-out-wo/

GPT4 recommends less than 128 as ideal though, IDK.

https://chat.openai.com/share/78040eb8-1861-4c61-8cb2-e0694c9da0b5

**Comment by skyl** [comment]
would be easy to change - moving to a note in the zpage project: https://github.com/orgs/free2z/projects/28/views/1
