### ISSUE TITLE
Page goes blank when changing username

### ISSUE THREAD

**Issue by lexihel** [free2z/zuu#65]
Hi guys! When you try to change the username and delete *every character* in the text box, the page goes blank. You only can see top tool bar and footer. To go back you have to hit "back" in your browser and all unsaved changes are deleted.

https://github.com/free2z/tuzi/assets/9355622/097d9b00-6c59-4622-bb4b-17815009c31b

**Comment by skyl** [comment]
should be fixed; might try other things abut changing username which we have not concentrated on much. There could be more bugs to find.
