### ISSUE TITLE
Italics or AI?

### ISSUE THREAD

**Issue by lexihel** [free2z/zuu#66]
The text formatting tool bar tells me we can use Ctrl + i to write text in Italics. But using that shortcut just calls the AI Generation prompt box. Tested on Firefox and 2 Chromium based browsers, Edge and Chrome

![imagen](https://user-images.githubusercontent.com/9355622/236376016-5cb79696-953b-46ff-990c-a2f621fcb04f.png)

![imagen](https://user-images.githubusercontent.com/9355622/236376042-38bf4335-bae1-430a-836f-ca3469d35906.png)

**Comment by skyl** [comment]
AI image should now be ctrl+m if you want to check
