### ISSUE TITLE
Suggestion on Zpages

### ISSUE THREAD

**Issue by gordonesroo** [free2z/zuu#67]
Greetings, Free2z team!

**I have 2 suggestions that I think could improve our user experience reading Zpages:**

1) Let there be a button, "back to top", like there is on WordPress blogs. It's a little arrow that when clicked, takes us to the top of the page. It is very useful especially in very long Zpages.

2) That at the end of our Zpages there is something (also like WordPress, sorry) that shows us similar posts from that author. That is usually called "related posts". It's a good way for a reader to see more content from that author and get hooked on this one.

Thanks.

**Comment by skyl** [comment]
I'll be looking at these on this board: https://github.com/orgs/free2z/projects/28/views/1

**Comment by skyl** [comment]
tracking in notes on the board
